### ISSUE TITLE
The technical direction

### ISSUE THREAD

**Issue by anapple96** [Ishadijcks/unknown-rpg#6]
I know, I know, this project is still in its infancy, but we should get this out of the way early, to avoid future conflicts.
So, what's the direction of the game? Idle? Half-idle? Fully active?
What're your plans for the game? Web RPG? Full blown RPG on Steam?
And, provide a better communication method. Issues are sorta limited.

**Comment by Ishadijcks** [comment]
This is a personal project. I'm not accepting contributions at this time, and will not for a very long time.
